version: '3'

services:
  web:
    image: nginx:1.19-alpine
    restart: always
    container_name: nginx-php
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/www
    ports:
      - '9001:80'
    networks:
      - app-network

  php:
    build: .
    restart: always
    container_name: php-5.6
    volumes:
      - ./:/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge